spring:
  datasource:
    url: jdbc:mysql://49.234.96.64:3306/liming?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: tianxiadi1
liming:
  #腾讯cos储存桶名称
  bucketName: cos-1257120178
  #bucket区域
  regionName: ap-shanghai
  #腾讯secretId
  secretId: AKIDMVRyrVz2vXtUpuETr2oLdgYAesrZRQXQ
  #腾讯secretKey
  secretKey: nKbeS8bpnV3Np5HF0ZyHOL5dEftqZ4LR
  #白名单
  whiteRoster: 127.0.0.1,0:0:0:0:0:0:0:1
  #是否开启ip拦截
  isCheckIp: false